### ISSUE TITLE
Unable to open /root/test.log

### ISSUE THREAD

**Issue by tcm0116** [xiaoyun94/gcov7-viewer#2]
Attempting to use this plugin fails because it tries to open `/root/test.log`, which is inaccessible to most users. Removing the following lines appears to resolve the issue:

https://github.com/xiaoyun94/gcov7-viewer/blob/4c6aced1e76b99ad69de65662adac31a745732eb/gcov7-json.py#L52-L55

**Comment by xiaoyun94** [comment]
you are right, this is a bad habit, and it is only tested via `root` user

**Comment by xiaoyun94** [comment]
version release `0.05` solves.
